### ISSUE TITLE
nothing seems to happen, no console output...

### ISSUE THREAD

**Issue by molecular** [codesoap/atto#15]
I've used the wallet a year or so ago. Just git pulled master branch and `go build ./cmd/atto  `, but still:

```
#> ./atto -b
```

nothing happens for many minutes

isn't there a debug flag I can set to see what's going on or where it might hang?

Feels like network trouble, but I can reach https://proxy.nanos.cc/proxy

**Comment by codesoap** [comment]
There is no `-b` flag for atto. You probably meant `atto b` (short for balance). Take a look at the README or `atto -h` again. It tells you this:

> The address, balance, representative and send subcommands expect a seed as the first line of their standard input.

So atto was doing nothing because you didn't give it a seed. If you stored your seed with `pass`, do something like `pass nano | atto b`.
