### ISSUE TITLE
FYI: atto is now available from AUR

### ISSUE THREAD

**Issue by kseistrup** [codesoap/atto#2]
ArchLinux users can now build and install `atto` from AUR:

```sh
  yay -S atto
```

⌘ https://aur.archlinux.org/packages/atto/

**Comment by codesoap** [comment]
That's great, thanks a lot! I have added a hint to the README in https://github.com/codesoap/atto/commit/12e074f29fb092106547e73a1e1e434912f37d24.

I'm not too familiar with Arch Linux, but is seems to me like there is no "standard AUR helper", so I decided to leave out installation instructions.
