### ISSUE TITLE
BIP39 Mnemonic Creation

### ISSUE THREAD

**Issue by zQueal** [codesoap/atto#3]
Looks like its possible to generate a BIP39 Mnemonic from a 64 character NANO seed: https://github.com/Joohansson/keytools/blob/master/src/tools/SeedTool.js

Would love to see this added to `atto`.

**Comment by codesoap** [comment]
I have chosen to exclude this feature from `atto` to keep the codebase and amount of dependencies small. If you need this feature, I would suggest using a different tool. This also fit's better into the UNIX-philosophy, which I'm trying to adhere to with `atto`. There are surely a lot of cli tools to generate BIP39 mnemonics and there are also some tools you can use directly from your browser; e.g.:

- https://tools.nanos.cc/?tool=seed (this is what you linked; [can also be downloaded](https://tools.nanos.cc/) to work offline)
- https://iancoleman.io/bip39/ (select "Show entropy details" and put the seed into the "Entropy" field)
