### ISSUE TITLE
Error: account has not yet been opened

### ISSUE THREAD

**Issue by xerobia-test** [codesoap/atto#5]
In the previous version, when I deposited some nano in a new account and then did `atto -a 2 b`, this would create a receive block for me to get those funds. 

Now, when I do that, it spits out "Error: account has not yet been opened"

**Comment by codesoap** [comment]
Should now be fixed through 17a9d20ae70588855a64e8bc86e3ccd937bbe2bb and 95ce62b8f4ec82c35ee9191d4e939bd2fd62d3bc.

Would you be willing to test again if atto now works for all your use cases? I'm going to test things again, too, but a second reviewer would be nice and you seem to find problems I miss :-) If all seems to work, I will create a new release later.

**Comment by codesoap** [comment]
I have now released [v1.4.0](https://github.com/codesoap/atto/releases/tag/v1.4.0) which hopefully reverts all previous regressions.
