### ISSUE TITLE
error cheking the balance of the account

### ISSUE THREAD

**Issue by el-cartas** [codesoap/atto#9]
when i write `pass nano | atto balance` on the console it returns `Error: received unexpected HTTP return code 500`. I've used nault.cc to test if the problen was with my account but it works perfectly, so the problem is with atto. Please fix this issue.

**Comment by codesoap** [comment]
Thanks for the report. It seems like the https://proxy.powernode.cc/proxy node is not accepting some requests anymore (for example for the `pending` action). Other nodes seem to be working. If you have built atto yourself, just go to `cmd/atto/config.go`, configure another node and re-install atto (as described in the README).

I'll investigate whats up with https://proxy.powernode.cc/proxy and set another default node if necessary.

**Comment by el-cartas** [comment]
thanks, it works now with an alternative node.

**Comment by codesoap** [comment]
I have not received a response from the node operator, but https://proxy.powernode.cc/proxy does support the `pending` action again. I guess the node was misconfigured for a few hours.
